version: 2

sources:
  - name: covid19_italy
    database: bigquery-public-data
    schema: covid19_italy
    tables:
      - name: data_by_province
      - name: data_by_region
      - name: national_trends
